NettuxPure_Gauntlet4_1_MapScripts::
	.byte 0

NettuxPure_Gauntlet4_EventScript_Encounters::
        msgbox NettuxPure_Gauntlet4_Text_Encounters, MSGBOX_DEFAULT
        closemessage
        end

NettuxPure_Gauntlet4_Text_Encounters:
        .string "POKéMON observed in this area:\l"
        .string "Gastly\l"
        .string "Zubat\l"
        .string "Makuhita\l"
        .string "Fennekin\l"
        .string "Mimikyu\l"
        .string "Fletchling\l"
        .string "Stunky\l"
        .string "Hoot Hoot\l"
        .string "Weedle\l"
        .string "Ekans$"
