NettuxPure_Gauntlet6_1_MapScripts::
	.byte 0

NettuxPure_Gauntlet6_EventScript_Encounters::
        msgbox NettuxPure_Gauntlet6_Text_Encounters, MSGBOX_DEFAULT
        closemessage
        end

NettuxPure_Gauntlet6_Text_Encounters:
        .string "POKéMON observed in this area:\l"
        .string "Gastly\l"
        .string "Aron\l"
        .string "Geodude\l"
        .string "Makuhita\l"
        .string "Meditite\l"
        .string "Ralts\l"
        .string "Sableye\l"
        .string "Geodude\l"
        .string "Zubat\l"
        .string "Fuecoco$"
