static const u16 sNettuxMartInventory_ZeroBadges[] = {
    ITEM_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_ETHER,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_OneBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_ETHER,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_TwoBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_ETHER,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_ThreeBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_ETHER,
    ITEM_PP_UP,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_FourBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_ETHER,
    ITEM_PP_UP,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_FiveBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_ETHER,
    ITEM_PP_UP,
    ITEM_MAX_ETHER,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_SixBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_FULL_HEAL,
    ITEM_ETHER,
    ITEM_PP_UP,
    ITEM_MAX_ETHER,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_SevenBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_MAX_POTION,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_FULL_HEAL,
    ITEM_ETHER,
    ITEM_PP_UP,
    ITEM_MAX_ETHER,
    ITEM_MAX_ETHER,
    ITEM_MAX_ELIXIR,
    ITEM_NONE
};

static const u16 sNettuxMartInventory_EightBadges[] = {
    ITEM_POTION,
    ITEM_SUPER_POTION,
    ITEM_HYPER_POTION,
    ITEM_MAX_POTION,
    ITEM_FULL_RESTORE,
    ITEM_ANTIDOTE,
    ITEM_BURN_HEAL,
    ITEM_ICE_HEAL,
    ITEM_AWAKENING,
    ITEM_PARALYZE_HEAL,
    ITEM_FULL_HEAL,
    ITEM_ETHER,
    ITEM_PP_UP,
    ITEM_MAX_ETHER,
    ITEM_MAX_ETHER,
    ITEM_MAX_ELIXIR,
    ITEM_ROTOM_CATALOG,
    ITEM_PP_MAX,
    ITEM_NONE
};

static const u16 *const sNettuxMartInventories[] =
{
    sNettuxMartInventory_ZeroBadges,
    sNettuxMartInventory_OneBadges,
    sNettuxMartInventory_TwoBadges,
    sNettuxMartInventory_ThreeBadges,
    sNettuxMartInventory_FourBadges,
    sNettuxMartInventory_FiveBadges,
    sNettuxMartInventory_SixBadges,
    sNettuxMartInventory_SevenBadges,
    sNettuxMartInventory_EightBadges
};

static const u16 sNettuxBattleInventory_ZeroBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_OneBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_TwoBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_ThreeBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_FourBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_WHITE_HERB,
    ITEM_MENTAL_HERB,
    ITEM_POWER_HERB,
    ITEM_MIRROR_HERB,
    ITEM_FOCUS_SASH,
    ITEM_LIFE_ORB,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_FiveBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_WHITE_HERB,
    ITEM_MENTAL_HERB,
    ITEM_POWER_HERB,
    ITEM_MIRROR_HERB,
    ITEM_FOCUS_SASH,
    ITEM_LIFE_ORB,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_SixBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_WHITE_HERB,
    ITEM_MENTAL_HERB,
    ITEM_POWER_HERB,
    ITEM_MIRROR_HERB,
    ITEM_FOCUS_SASH,
    ITEM_LIFE_ORB,
    ITEM_CLEAR_AMULET,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_SevenBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_WHITE_HERB,
    ITEM_MENTAL_HERB,
    ITEM_POWER_HERB,
    ITEM_MIRROR_HERB,
    ITEM_FOCUS_SASH,
    ITEM_LIFE_ORB,
    ITEM_CLEAR_AMULET,
    ITEM_NONE
};

static const u16 sNettuxBattleInventory_EightBadges[] = {
    ITEM_SILK_SCARF,
    ITEM_CHARCOAL,
    ITEM_MYSTIC_WATER,
    ITEM_MAGNET,
    ITEM_MIRACLE_SEED,
    ITEM_NEVER_MELT_ICE,
    ITEM_BLACK_BELT,
    ITEM_POISON_BARB,
    ITEM_SOFT_SAND,
    ITEM_SHARP_BEAK,
    ITEM_TWISTED_SPOON,
    ITEM_SILVER_POWDER,
    ITEM_DRAGON_FANG,
    ITEM_BLACK_GLASSES,
    ITEM_SNOWBALL,
    ITEM_HARD_STONE,
    ITEM_SPELL_TAG,
    ITEM_METAL_COAT,
    ITEM_WHITE_HERB,
    ITEM_MENTAL_HERB,
    ITEM_POWER_HERB,
    ITEM_MIRROR_HERB,
    ITEM_FOCUS_SASH,
    ITEM_LIFE_ORB,
    ITEM_CLEAR_AMULET,
    ITEM_NONE
};

static const u16 *const sNettuxBattleInventories[] =
{
    sNettuxBattleInventory_ZeroBadges,
    sNettuxBattleInventory_OneBadges,
    sNettuxBattleInventory_TwoBadges,
    sNettuxBattleInventory_ThreeBadges,
    sNettuxBattleInventory_FourBadges,
    sNettuxBattleInventory_FiveBadges,
    sNettuxBattleInventory_SixBadges,
    sNettuxBattleInventory_SevenBadges,
    sNettuxBattleInventory_EightBadges
};

static const u16 sNettuxTrainingInventory_ZeroBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_OneBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_TwoBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_ThreeBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_DAWN_STONE,
    ITEM_DUSK_STONE,
    ITEM_MAGMARIZER,
    ITEM_ELECTIRIZER,
    ITEM_VENUSAURITE,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_FourBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_DAWN_STONE,
    ITEM_DUSK_STONE,
    ITEM_MAGMARIZER,
    ITEM_ELECTIRIZER,
    ITEM_VENUSAURITE,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_UPGRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_FiveBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_DAWN_STONE,
    ITEM_DUSK_STONE,
    ITEM_MAGMARIZER,
    ITEM_ELECTIRIZER,
    ITEM_VENUSAURITE,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_UPGRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_SixBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_DAWN_STONE,
    ITEM_DUSK_STONE,
    ITEM_MAGMARIZER,
    ITEM_ELECTIRIZER,
    ITEM_VENUSAURITE,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_UPGRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_SevenBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_DAWN_STONE,
    ITEM_DUSK_STONE,
    ITEM_MAGMARIZER,
    ITEM_ELECTIRIZER,
    ITEM_VENUSAURITE,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_UPGRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_CORNERSTONE_MASK,
    ITEM_WELLSPRING_MASK,
    ITEM_HEARTHFLAME_MASK,
    ITEM_NONE
};

static const u16 sNettuxTrainingInventory_EightBadges[] = {
    ITEM_ABILITY_CAPSULE,
    ITEM_ABILITY_PATCH,
    ITEM_FIRE_STONE,
    ITEM_WATER_STONE,
    ITEM_THUNDER_STONE,
    ITEM_LEAF_STONE,
    ITEM_MOON_STONE,
    ITEM_SUN_STONE,
    ITEM_DAWN_STONE,
    ITEM_DUSK_STONE,
    ITEM_MAGMARIZER,
    ITEM_ELECTIRIZER,
    ITEM_VENUSAURITE,
    ITEM_BLASTOISINITE,
    ITEM_BEEDRILLITE,
    ITEM_PIDGEOTITE,
    ITEM_ALAKAZITE,
    ITEM_SLOWBRONITE,
    ITEM_GENGARITE,
    ITEM_KANGASKHANITE,
    ITEM_PINSIRITE,
    ITEM_GYARADOSITE,
    ITEM_AERODACTYLITE,
    ITEM_AMPHAROSITE,
    ITEM_STEELIXITE,
    ITEM_SCIZORITE,
    ITEM_HERACRONITE,
    ITEM_HOUNDOOMINITE,
    ITEM_TYRANITARITE,
    ITEM_SCEPTILITE,
    ITEM_BLAZIKENITE,
    ITEM_SWAMPERTITE,
    ITEM_GARDEVOIRITE,
    ITEM_SABLENITE,
    ITEM_MAWILITE,
    ITEM_AGGRONITE,
    ITEM_MEDICHAMITE,
    ITEM_MANECTITE,
    ITEM_SHARPEDONITE,
    ITEM_CAMERUPTITE,
    ITEM_ALTARIANITE,
    ITEM_BANETTITE,
    ITEM_ABSOLITE,
    ITEM_GLALITITE,
    ITEM_SALAMENCITE,
    ITEM_METAGROSSITE,
    ITEM_LOPUNNITE,
    ITEM_GARCHOMPITE,
    ITEM_LUCARIONITE,
    ITEM_ABOMASITE,
    ITEM_GALLADITE,
    ITEM_UPGRADE,
    ITEM_DUBIOUS_DISC,
    ITEM_CORNERSTONE_MASK,
    ITEM_WELLSPRING_MASK,
    ITEM_HEARTHFLAME_MASK,
    ITEM_NONE
};

static const u16 *const sNettuxTrainingInventories[] =
{
    sNettuxTrainingInventory_ZeroBadges,
    sNettuxTrainingInventory_OneBadges,
    sNettuxTrainingInventory_TwoBadges,
    sNettuxTrainingInventory_ThreeBadges,
    sNettuxTrainingInventory_FourBadges,
    sNettuxTrainingInventory_FiveBadges,
    sNettuxTrainingInventory_SixBadges,
    sNettuxTrainingInventory_SevenBadges,
    sNettuxTrainingInventory_EightBadges
};

static const u16 sNettuxTMInventory_ZeroBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_OneBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_TwoBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_ThreeBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_FourBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_FiveBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_SixBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_SevenBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxTMInventory_EightBadges[] = {
    ITEM_NONE
};

static const u16 *const sNettuxTMInventories[] =
{
    sNettuxTMInventory_ZeroBadges,
    sNettuxTMInventory_OneBadges,
    sNettuxTMInventory_TwoBadges,
    sNettuxTMInventory_ThreeBadges,
    sNettuxTMInventory_FourBadges,
    sNettuxTMInventory_FiveBadges,
    sNettuxTMInventory_SixBadges,
    sNettuxTMInventory_SevenBadges,
    sNettuxTMInventory_EightBadges
};

static const u16 sNettuxEvolveInventory_ZeroBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_OneBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_TwoBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_ThreeBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_FourBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_FiveBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_SixBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_SevenBadges[] = {
    ITEM_NONE
};

static const u16 sNettuxEvolveInventory_EightBadges[] = {
    ITEM_NONE
};

static const u16 *const sNettuxEvolveInventories[] =
{
    sNettuxEvolveInventory_ZeroBadges,
    sNettuxEvolveInventory_OneBadges,
    sNettuxEvolveInventory_TwoBadges,
    sNettuxEvolveInventory_ThreeBadges,
    sNettuxEvolveInventory_FourBadges,
    sNettuxEvolveInventory_FiveBadges,
    sNettuxEvolveInventory_SixBadges,
    sNettuxEvolveInventory_SevenBadges,
    sNettuxEvolveInventory_EightBadges
};

